DATASET: %(dataset)s

DATA_FOLDER: %(data_folder)s

config_preprocess:
  msd_spec:
    audio_folder: /home/jpons/audio/msd/
    hop: 256
    identifier: msd
    index_file: index/msd/index_msd.tsv
    machine_i: 0
    n_fft: 512
    n_machines: 1
    n_mels: 96
    num_processing_units: 20
    resample_sr: 16000
    spectrogram_type: mel
    type: time-freq
  mtt_spec:
    audio_folder: /home/jpons/audio/mtt/
    hop: 256
    identifier: mtt
    index_file: index/mtt/index_mtt.tsv
    machine_i: 0
    n_fft: 512
    n_machines: 1
    n_mels: 96
    num_processing_units: 20
    resample_sr: 16000
    spectrogram_type: mel
    type: time-freq
  mtgdb_spec:
    audio_folder: %(audio_folder)s
    hop: 256
    identifier: %(identifier)s
    index_audio_file: %(index_audio_file)s
    index_repr_file: %(index_repr_file)s
    machine_i: 0
    n_fft: 512
    n_machines: 1
    n_mels: 96
    num_processing_units: 20
    resample_sr: 16000
    spectrogram_type: mel
    type: time-freq

config_train:
  spec:
    audio_representation_folder: audio_representation/
    batch_size: 32
    epochs: 600
    gt_train: %(gt_train)s
    gt_val: %(gt_val)s
    gt_test: %(gt_test)s
    learning_rate: 0.001
    load_model: null
    model_number: 12
    n_frames: 187
    name_run: ''
    num_classes_dataset: %(num_classes_dataset)s
    optimizer: Adam
    pad_short: repeat-pad
    param_train_sampling: 1
    patience: 75
    pre_processing: logC
    train_sampling: random
    val_batch_size: 32
    weight_decay: 1.0e-05
    n_folds: %(n_folds)s
    fold: %(fold)s
